"use client";
import { Inter } from "next/font/google";
import StyledComponentsRegistry from "./registry";
import { GlobalStyle } from "../styles/global";
import { ThemeProvider } from "styled-components";
import THEME from "../styles/theme";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <StyledComponentsRegistry>
        <ThemeProvider theme={THEME}>
          <GlobalStyle />
          <body className={inter.className}>{children}</body>
        </ThemeProvider>
      </StyledComponentsRegistry>
    </html>
  );
}
